# OAuth Configuration
# You'll need to create a GitHub OAuth app and add these credentials
# backend:
#   name: github
#   repo: aurel/fairshareapps
#   branch: main
#   base_url: https://kellysaintdenny.com

# For now, let's use the local backend for testing
backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Reading Time", name: "readingTime", widget: "string", required: false}

  - name: "pages"
    label: "Pages"
    folder: ""
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "_data/site.yml"
        label: "Site Configuration"
        name: "site"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Social Links", name: "social", widget: "object", fields: [
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "ORCID", name: "orcid", widget: "string", required: false},
              {label: "Google Scholar", name: "google_scholar", widget: "string", required: false}
            ]}

publish_mode: editorial_workflow

editor:
  preview: false
